config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "home#welcome"
  resources :genres, only: :index do
    member do
      get "movies"
    end
  end
  resources :commenters, only: :index
  resources :movies, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    member do
      get :send_info
    end
    collection do
      get :export
    end
  end

  mount Movies::API => '/'

end

app/controllers/api/movies_controller.rb
class Api::MoviesController < ApplicationController
  def index
    @with_details = params[:details] and params[:details] == 'true';
    @movies = Movie.all
  end
end

app/controllers/api/v1/movies_controller.rb
module Api
  module V1
    class MoviesController < ActionController::API
      # GET api/v1/movies
      # GET api/v1/movies?include_genre=true
      def index
        movies = Movie.all.includes(:genre)
        render json: movies, each_serializer: assign_serializer, status: 201
      end

      # GET api/v1/movies/:id
      # GET api/v1/movies/:id?include_genre=true
      def show
        movie = Movie.includes(:genre).find(params[:id])
        render json: movie, serializer: assign_serializer, status: 201
      rescue ActiveRecord::RecordNotFound
        render json: { error: I18n.t('movie.not_found') }, status: :not_found
      end

      private

      def assign_serializer
        params[:include_genre].present? ? Movies::DetailedSerializer : Movies::SimpleSerializer
      end
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:send_info]

  def index
    @movies = Movie.all.decorate
  end

  def show
    @movie = Movie.find(params[:id]).decorate
    @comments = @movie.comments.ordered.decorate
  end

  def send_info
    @movie = Movie.find(params[:id])
    Delayed::Job.enqueue(MovieInfoMailerJob.new(current_user.id, @movie.id))
    redirect_back(fallback_location: root_path, notice: "Email sent with movies info")
  end

  def export
    file_path = "tmp/movies.csv"
    MovieExporter.new.call(current_user, file_path)
    redirect_to root_path, notice: "Movies exported"
  end
end

app/views/movies/_comments_table.html.haml
%table.table.table-striped
  %caption Comments
  %thead
    %tr
      %td created_at
      %td email
      %td comment
      %td
  %tbody
    - @movie.comments.order(id: :desc).each_with_index do |comment, i|
      - if comment.id  #prevent to show empty comment from build (when comment for current_user doesn't exists)
        %tr
          %td= comment.created_at.strftime("%Y-%m-%d %H:%M:%S")
          %td= comment.user.email
          %td= comment.body
          %td= link_to 'delete', [@movie, comment], :method => :delete, data: {confirm: "Are you sure?"} if current_user == comment.user
        

app/views/movies/_form.html.haml
= form_for [@movie, @comment], method: :post do |f|
  = f.label 'Comment'
  %div.fields
    = f.text_area :body, class: 'form-control'
  = f.submit "Add comment"

app/views/movies/_movies_table.html.haml
%table.table.table-striped
  %tbody
    - movies.each_with_index do |movie, i|
      %tr
        %td= i + 1
        %td
          %img.img-rounded{ src: movie.poster }
        %td
          %h4
            = link_to movie.title, movie_path(movie)
            = movie.rating
          %p
            %strong
              -#= link_to movies.genre.name, movies_genre_path(movies.genre)
            = ' (' + movie.released_at.to_s + ')'
          %p= movie.description
          %p= movie.plot

app/views/movies/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Movies
    = will_paginate @movies 
    = render 'movies_table', movies: @movies

app/views/movies/show.html.haml
.row
  .col-md-12.col-lg-12
    %h1
      = @movie.title
      = @movie.rating
.row
  .col-md-2.col-lg-2
    %img.img-rounded{ src: @movie.poster }
  .col-md-10.col-lg-10
    %p= @movie.description
    %p= @movie.plot
- if user_signed_in?
  %p= link_to 'Email me details about this movies', send_info_movie_path(@movie), class: 'btn btn-sm btn-default'
  - unless @movie.is_commented_by?(current_user)
    = render 'movies/comments/form', movie: @movie
  = render 'movies/comments/comments_table', comments: @comments