config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "home#welcome"
  resources :genres, only: :index do
    member do
      get "movies"
    end
  end
  resources :commenters, only: :index
  resources :movies, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    member do
      get :send_info
    end
    collection do
      get :export
    end
  end

  mount Movies::API => '/'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Pairguru App', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Movies', movies_path
%li= link_to 'Genres', genres_path
- if user_signed_in?
  %li= link_to 'Export', export_movies_path
%li= link_to 'Top commenters', commenters_path

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li= link_to 'Logout', destroy_user_session_path, method: :delete
- else
  %li= link_to 'Login', new_user_session_path
  %li= link_to 'Register', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Pairguru'
    %meta{ name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Props'}" }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #announcements-region
    %header
      #header-region
        = render 'layouts/navigation'
    %main
      .container
        #main-region
        = render 'layouts/messages'
        = yield
    %footer.text-center
      Magic by
      = link_to 'netguru', 'https://netguru.co'